name: Deploy ke VPS

on:
  push:
    branches: ["aws"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # - name: Copy isi repository ke existing folder
      #   uses: appleboy/scp-action@master
      #   env:
      #     HOST: ${{ secrets.HOST }}
      #     USERNAME: ${{ secrets.USERNAME }}
      #     PORT: ${{ secrets.PORT }}
      #     PASSWORD: ${{ secrets.PASSWORD }}
      #   with:
      #     source: "."
      #     target: "/home/kel5/tb_temp"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: git pull origin aws
