name: Deploy ke VPS

on:
  push:
    branches: ["aws"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Pull dari repository ini
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
            cd /home/kel5/tb_temp
            git pull origin aws

      # - name: Remove semua container dan images yang sudah ada
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     USERNAME: ${{ secrets.USERNAME }}
      #     PORT: ${{ secrets.PORT }}
      #     PASSWORD: ${{ secrets.PASSWORD }}
      #     script: |
      #       docker stop $(docker ps -aq)
      #       docker rm $(docker ps -aq)

      - name: Build image baru dan container baru
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
            cd /home/kel5/tb_temp
            docker build -t tokobangunan .
            docker run -d -it -p 8081:80 tokobangunan
